version: '3.4'

services:
  vnpy:
    image: vnpy
    build:
      context: .
      dockerfile: ./Dockerfile
    # volumes:
    #   - .:/app/src
    command: ["sh", "-c", "pip install debugpy -t /tmp && python3 /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 setup.py "]
    ports:
      - 5678:5678
